### ISSUE TITLE
improve orientation for profile images

### ISSUE THREAD

**Issue by jonassindal** [cfdp/foelgeven#1]
Profile images are often uploaded while oriented the wrong way. The orientation looks right to the user when viewing the image in windows, but this is not reflected when uploaded to følgeven.dk.

**Comment by jonassindal** [comment]
@kasper-openUsource Vi har brug for at få dette issue løst relativt hurtigt. Hvornår kan I se på det?

**Comment by jonassindal** [comment]
@kasper-openUsource Denne opgave må gerne komme før ung økonomi, og den må gerne udrulles for sig selv, eventuelt tjek om den kan løses direkte på live sitet, og grib gerne fat i @benjamin-dk , hvis live-redigeringen kræver ekstra rygdækning.

**Comment by jonassindal** [comment]
Deadline denne uge @kasper-openUsource

**Comment by kasper-openUsource** [comment]
Løst med imagecache_actions og aspect-ratio
Se fix på denne profil som tidligere havde forkert orientering:
https://foelgeven.dk/user/579/extended

**Comment by jonassindal** [comment]
Hej Kasper - er den deployed til livesite?

**Comment by kasper-openUsource** [comment]
Ja. Den er deployed.

Mvh kasper

Den 23. jun. 2017 16.33 skrev "jonassindal" <notifications@github.com>:

**Comment by jonassindal** [comment]
Hej Kasper
Jeg har brug for at vide lidt mere om, hvordan løsningen virker, så jeg kan forklare det for koordinatorerne, som skal supporte brugerne i at oprette profiler på sitet. Giv gerne et ring når du har tid :)

—
Jonas Sindal Birk
Konceptudvikler og foredragsholder  |  Center for Digital Pædagogik
☎ +45 21766708  | jonassindal@cfdp.dk  |  cfdp.dk
netstof.dk  |  cyberhus.dk  | følgeven.dk  |  mitassist.dk
    


Den 26. juni 2017 kl. 08.00.51, kasper-openUsource (notifications@github.com) skrev:

Ja. Den er deployed.

Mvh kasper

Den 23. jun. 2017 16.33 skrev "jonassindal" <notifications@github.com>:
